#! /bin/bash

# The Steam client is known to call this script with the following parameter combinations:
# steamos-update --supports-duplicate-detection     -- should do nothing
# steamos-update --enable-duplicate-detection check -- should check for update
# steamos-update check                              -- should check for update
# steamos-update --enable-duplicate-detection       -- should perform an update
# steamos-update                                    -- should perform an update

echo "---" >> /home/gamer/steam-update.log
echo "Arguments: $@" >> /home/gamer/steam-update.log

EXIT=false
CHECK=false
RUN_UPDATE=true
for arg in "$@"; do
  if [ "$arg" = "check" ]; then
    CHECK=true
    echo "CHECK=true" >> /home/gamer/steam-update.log
  fi

  if [ "$arg" = "--enable-duplicate-detection" ]; then
    RUN_UPDATE=true
    echo "RUN_UPDATE=true" >> /home/gamer/steam-update.log
  fi
  
  if [ "$arg" = "--supports-duplicate-detection" ]; then
    EXIT=true
    echo "EXIT=true" >> /home/gamer/steam-update.log
  fi
done

if [ "$EXIT" = "true" ]; then
  echo "Exit..." >> /home/gamer/steam-update.log
  exit 0
fi

HAS_UPDATES=false
if [ "$CHECK" = "true" ] || [ "$RUN_UPDATE" = "true" ]; then
  echo "Checking updates..." >> /home/gamer/steam-update.log
  
  # check if management has updates
  cd /home/gamer/ReignOS
  git fetch
  git_local=$(git rev-parse @)
  git_upstream=$(git rev-parse @{u} 2>/dev/null)
  if [[ "$git_local" != "$git_upstream" ]]; then
    HAS_UPDATES=true
  fi
  
  # check if pacman updates exist
  if [ "$HAS_UPDATES" = "false" ]; then
    sudo pacman -Sy
    if pacman -Qu &> /dev/null; then
        HAS_UPDATES=true
    fi
  fi
  
  # check if yay updates exist
  if [ "$HAS_UPDATES" = "false" ]; then
    yay -Sy
    HAS_UPDATES=false
    if yay -Qu --ignore aw87559-firmware &> /dev/null; then
        HAS_UPDATES=true
    fi
  fi
  
  # only exit if check only
  if [ "$CHECK" = "true" ]; then
    if [ "$HAS_UPDATES" = "false" ]; then
      # just tell steam there are no updates
      echo "No updates" >> /home/gamer/steam-update.log
      exit 7
    else
      # tell steam there is update
      echo "Has updates" >> /home/gamer/steam-update.log
      exit 0
    fi
  fi
fi

if [ "$RUN_UPDATE" = "true" ] && [ "$CHECK" = "false" ] && [ "$HAS_UPDATES" = "true" ]; then
  echo "Updating..." >> /home/gamer/steam-update.log

  # force exit ReignOS managment
  sudo pkill ReignOS.Service
  sudo pkill ReignOS.Bootloader
  
  # run ReignOS updates
  cd /home/gamer/ReignOS/Managment/ReignOS.Bootloader/bin/Release/net8.0/linux-x64/publish
  ./Update.sh
  
  (
    sudo pkill steam
    sleep 10
    loginctl terminate-user gamer
  ) &
fi

# just exit saying no updates by default
echo "Done" >> /home/gamer/steam-update.log
exit 7